window.noname_update={
	version:'2.5.1.1',
	update:'2.5.1.1',
	changeLog:[
		'<strong>咕咕咕的更新：</strong>\n1.修复了潘皓天、葛辰启、俞瑞佳和卢俊雨的相关BUG。\n2.因为香泡四杰指的四个人分别去了饿中、学车和菊中，所以香泡四杰在母校模式新增对饿中、学车和菊中相关装备特殊技能的支持；3.修复吴孟祥和姚皇燊照片问题。',
		'以下为最后一次常规更新内容：',
		'修改了二中之梦和长河之梦',
		'为二中之梦、学军之梦、十四之梦添加了母校模式',
		'处理好了葛辰启和潘皓天的最终版本，并添加了相关图片和皮肤',
		'将21-27号（老学号）的怀旧版本迁移到了最终包',
		'将其他的毕业季歌曲与原先的《干杯》合成了一个背景音乐，可通过选项->音效->背景音乐->“毕业”设置',
		'整合了《流浪地球》相关背景音乐，但不会有主题了',
		'为我们的初中三年新添加了背景“同学”和主题“同学”',
		'感谢大家初中三年的陪伴！'
	],
	files:[
		'card/extra.js',
		'card/standard.js',
		'card/guozhan.js',
		'character/retps.js',
		'character/tps.js',
		'game/package.js',
		'image/card/hualiu.png',
		'image/card/jingfanma.png',
		'image/character/wumengxiang.jpg',
		'image/character/yaohuangshen.jpg',
	]
};
