window.noname_update={
	version:'2.0',
	update:'2.0',
	changeLog:[
		'太平杀离线版出炉！'
	],
	files:[
		'card/standard.js',
		'card/extra.js',
		'card/standard.js',
		'character/extra.js',
		'character/diy.js',
		'character/standard.js',
	]
};
